### ISSUE TITLE
building doesn't seem to work

### ISSUE THREAD

**Issue by sdwfrost** [JDureau/H1N1-London-2009#1]
```
cd SEIR_beta_t
plom build -t map.json --local
```

leads to

```
FAIL: in theta parameter [object Object] group all, {"value":0.935463} is not a number
```

plom builds the dengue model without complaint. I'm using plom v. 0.8.6, compiled from the github source, built on Linux Mint 14. Let me know what additional debugging information is helpful, so I can provide in future.

Best
Simon

**Comment by JDureau** [comment]
Hi Simon,

Thanks a lot for raising this issue. 
map.json was in a former version's format. It should work now.

Cheers,

Joseph
